prod:
  image: registry.cnode.fr/react-seed:0.1.0
  container_name: react-seed
  expose:
   - "5000"
  environment:
    VIRTUAL_HOST: 'react-seed.cnode.fr'
    API_SERVER_PORT: 443
    API_SERVER_HOSTNAME: "https://api.react-seed.fr"
    SERVER_RENDERING: 1
    REDUX_DEVTOOLS: 0
    FRONTEND_SERVER_PORT: 5000
    NODE_ENV: production

staging:
  image: registry.cnode.fr/react-seed:develop
  container_name: react-seed-staging
  expose:
   - "5000"
  environment:
    VIRTUAL_HOST: 'react-seed-staging.cnode.fr'
    API_SERVER_PORT: 443
    API_SERVER_HOSTNAME: "https://api.react-seed.fr"
    SERVER_RENDERING: 1
    REDUX_DEVTOOLS: 0
    FRONTEND_SERVER_PORT: 5000
    DEBUG: "react-seed-*"

local:
  build: .
  container_name: react-seed-local
  ports:
    - "5000:5000"
  environment:
    API_SERVER_PORT: 443
    API_SERVER_HOSTNAME: "https://api.react-seed.fr"
    SERVER_RENDERING: 1
    REDUX_DEVTOOLS: 0
    FRONTEND_SERVER_PORT: 5000
    NODE_ENV: production

local-develop:
  build: .
  container_name: react-seed-local-develop
  ports:
    - "5000:5000"
  environment:
    API_SERVER_PORT: 443
    API_SERVER_HOSTNAME: "https://api.react-seed.fr"
    SERVER_RENDERING: 1
    REDUX_DEVTOOLS: 0
    FRONTEND_SERVER_PORT: 5000
    DEBUG: "react-seed-*"
