prod:
  image: registry.cnode.fr/ReactSeed:0.2.0
  container_name: ReactSeed
  expose:
   - "5000"
  environment:
    SERVER_RENDERING: 1
    REDUX_DEVTOOLS: 0
    FRONTEND_SERVER_PORT: 5000
    NODE_ENV: production

staging:
  image: registry.cnode.fr/ReactSeed:develop
  container_name: ReactSeed-staging
  expose:
   - "5000"
  environment:
    SERVER_RENDERING: 1
    REDUX_DEVTOOLS: 0
    FRONTEND_SERVER_PORT: 5000
    DEBUG: "ReactSeed-*"

local:
  build: .
  container_name: ReactSeed-local
  ports:
    - "5000:5000"
  environment:
    SERVER_RENDERING: 1
    REDUX_DEVTOOLS: 0
    FRONTEND_SERVER_PORT: 5000
    NODE_ENV: production

local-develop:
  build: .
  container_name: ReactSeed-local-develop
  ports:
    - "5000:5000"
  environment:
    SERVER_RENDERING: 1
    REDUX_DEVTOOLS: 0
    FRONTEND_SERVER_PORT: 5000
    DEBUG: "ReactSeed-*"
